// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgrfsuewkayqrobdfesa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncmZzdWV3a2F5cXJvYmRmZXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjU2NDYsImV4cCI6MjA3NTUwMTY0Nn0.FG9Qb2UU169_6kTP6oFqTvOaBioxHCA1TKiBRxumibk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
